on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - run: make
    - run: make check
